name: Roteiro

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST_USER: ${{ vars.HOST_USER }}
  HOST_IP: ${{ vars.HOST_IP }}

on:
  push:
    branches: [ "main" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Create JAR file
        run: mvn clean package

      - name: login to Docker Hub
        run: |
          docker login -u nogueiralegacy -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build image
        run: docker-compose build

      - name: tag image
        run: docker tag provax nogueiralegacy/provax:latest

      - name: push image
        run: |
          docker push nogueiralegacy/provax:latest

  deploy:
    needs: publish_image
    runs-on: ubuntu-latest
    steps:
      - name: Connect to host
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          ls
          ssh -i key.pem -o StrictHostKeyChecking=no $HOST_USER@$HOST_IP source /root/projects/script.sh
